export const initialTelemetry = {
  kpis: {
    openIncidents: 42,
    reopenedEscalated: 8,
    avgReassignments: 1.8,
    mttrHours: 2.4,
    slaComplianceRate: 93.6,
    activeThreatLevel: "ELEVATED",
  },
  priorityDistribution: [
    { priority: "critical", label: "Critical Priority", count: 9, percentage: 85, color: "#ff3344" },
    { priority: "high", label: "High Priority", count: 18, percentage: 65, color: "#ff8800" },
    { priority: "medium", label: "Medium Priority", count: 32, percentage: 45, color: "#ffd600" },
    { priority: "low", label: "Low Priority", count: 14, percentage: 25, color: "#00ff66" },
  ],
  slaBreakdown: [
    { month: "Jan", compliant: 92, breached: 8 },
    { month: "Feb", compliant: 88, breached: 12 },
    { month: "Mar", compliant: 95, breached: 5 },
    { month: "Apr", compliant: 91, breached: 9 },
    { month: "May", compliant: 94, breached: 6 },
    { month: "Jun", compliant: 96, breached: 4 },
  ],
  mitreTechniques: [
    { code: "T1117", name: "Regsvr32 Proxy Execution", count: 15, severity: "critical" },
    { code: "T1047", name: "WMI Command Execution", count: 11, severity: "high" },
    { code: "T1086", name: "PowerShell Script Injection", count: 8, severity: "critical" },
    { code: "T1490", name: "Inhibit System Recovery / VSS", count: 5, severity: "high" },
    { code: "T1204", name: "Malicious User Execution", count: 4, severity: "medium" },
    { code: "T1193", name: "Spearphishing Attachment", count: 3, severity: "medium" },
  ],
  topHosts: [
    { host: "sec-ops-srv01", incidents: 14, status: "critical", ip: "10.0.1.45" },
    { host: "db-cluster-node2", incidents: 9, status: "warning", ip: "10.0.2.12" },
    { host: "ad-dc-master", incidents: 6, status: "warning", ip: "10.0.0.5" },
    { host: "gateway-proxy-eu", incidents: 4, status: "normal", ip: "192.168.1.1" },
    { host: "workstation-dev-21", incidents: 2, status: "normal", ip: "10.0.5.88" },
  ],
  sampleIncidents: [
    {
      _id: "inc-101",
      title: "Ransomware canary file modification detected",
      description: "Automated honeypot alert triggered on file server 04. Canary files encrypted.",
      severity: "critical",
      status: "investigating",
      affectedSystems: ["fs04.corp", "backup-nas01"],
      reportedBy: { name: "System Watchdog", email: "sec-bot@corp.net" },
      createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    {
      _id: "inc-102",
      title: "Repeated SSH brute force attempts on Bastion",
      description: "Over 8,400 unauthorized access attempts recorded from external ASN within 10 minutes.",
      severity: "high",
      status: "reported",
      affectedSystems: ["bastion-eu-west"],
      reportedBy: { name: "Alex Chen (Analyst)", email: "alex.c@cyber.org" },
      createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    },
    {
      _id: "inc-103",
      title: "Abnormal data egress to unauthorized external IP",
      description: "Surge of 14GB outbound traffic detected on port 443 towards unverified IP range.",
      severity: "high",
      status: "contained",
      affectedSystems: ["workstation-eng-09"],
      reportedBy: { name: "Network Monitor", email: "net-sec@corp.net" },
      createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    },
    {
      _id: "inc-104",
      title: "Suspicious PowerShell command line arguments",
      description: "Base64 encoded payload executed in context of user session on workstation.",
      severity: "medium",
      status: "resolved",
      affectedSystems: ["fin-ws-11"],
      reportedBy: { name: "EDR Agent", email: "edr@corp.net" },
      createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    },
  ],
  sampleTickets: [
    {
      _id: "tick-201",
      title: "Firewall rule update for zero-trust endpoint sync",
      description: "Require port 8443 open between segment A and microsegment B for mutual TLS.",
      priority: "high",
      status: "in_progress",
      category: "security",
      reportedBy: { name: "Marcus Brody", email: "m.brody@corp.net" },
      slaDeadline: new Date(Date.now() + 3600000 * 1.5).toISOString(),
      escalated: false,
      createdAt: new Date(Date.now() - 3600000 * 2.5).toISOString(),
    },
    {
      _id: "tick-202",
      title: "Emergency MFA token reset for compromised admin account",
      description: "Account flagged for anomalous location login. Reset hardware key credentials.",
      priority: "critical",
      status: "escalated",
      category: "security",
      reportedBy: { name: "Sarah Connor", email: "s.connor@corp.net" },
      slaDeadline: new Date(Date.now() - 3600000 * 0.4).toISOString(),
      escalated: true,
      createdAt: new Date(Date.now() - 3600000 * 1.8).toISOString(),
    },
    {
      _id: "tick-203",
      title: "VPN Gateway certificate renewal expiring in 48h",
      description: "GlobalProtect gateway SSL cert expiration notification received.",
      priority: "medium",
      status: "open",
      category: "IT",
      reportedBy: { name: "DevOps Team", email: "devops@corp.net" },
      slaDeadline: new Date(Date.now() + 3600000 * 6).toISOString(),
      escalated: false,
      createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    },
    {
      _id: "tick-204",
      title: "Patch deployment failure on domain controller replica",
      description: "Cumulative security update KB5034441 returned error code 0x80070643.",
      priority: "high",
      status: "resolved",
      category: "IT",
      reportedBy: { name: "IT SysAdmin", email: "admin@corp.net" },
      slaDeadline: new Date(Date.now() + 3600000 * 8).toISOString(),
      escalated: false,
      createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    },
  ],
  sampleAuditLogs: [
    {
      _id: "audit-1",
      action: "TICKET_AUTO_ESCALATED",
      performedBy: { name: "Cron SLA Daemon", role: "system" },
      targetCollection: "tickets",
      details: { reason: "Deadline approaching within 30m window", threshold: "critical" },
      createdAt: new Date(Date.now() - 600000).toISOString(),
    },
    {
      _id: "audit-2",
      action: "INCIDENT_REPORTED",
      performedBy: { name: "Security Analyst", role: "security_analyst" },
      targetCollection: "incidents",
      details: { severity: "critical", title: "Ransomware canary triggered" },
      createdAt: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      _id: "audit-3",
      action: "TICKET_ASSIGNED",
      performedBy: { name: "Admin", role: "admin" },
      targetCollection: "tickets",
      details: { assignedTo: "Support Agent Lead" },
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      _id: "audit-4",
      action: "USER_LOGIN",
      performedBy: { name: "Security Analyst", role: "security_analyst" },
      targetCollection: "users",
      details: { ip: "127.0.0.1", method: "JWT Bearer" },
      createdAt: new Date(Date.now() - 7200000).toISOString(),
    },
  ],
};
